### ISSUE TITLE
Support to schedule from config

### ISSUE THREAD

**Issue by ppiwow-apay** [arhill05/backstage-plugin-search-backend-module-azure-devops-wiki#8]
Hi,

Currentyly plugin has some defualt scheduler. Should be able to read from `app-config.yaml` like others

```
search:
  engine: pg
  collators:
    catalog:
      schedule:
        # supports cron, ISO duration, "human duration" as used in code
        frequency: { minutes: 60 }
        # supports ISO duration, "human duration" as used in code
        timeout: { minutes: 15 }
        initialDelay: { minutes: 1 }
```

something like that:

```
 const schedule = config.has('search.collators.azureDevopsWiki.schedule')
          ? readTaskScheduleDefinitionFromConfig(
              config.getConfig('search.collators.announcements.schedule'),
            )
          : defaultSchedule;
```
